version: "3"

services:
    php:
        container_name: docker_php
        build:
            context: docker/php
            dockerfile: Dockerfile
        networks:
            - docker_php
        volumes:
            - ./www:/var/www
            - ./docker/php/conf.d/custom-dev.ini:/usr/local/etc/php/conf.d/custom.ini

    nginx:
        container_name: docker_nginx
        image: nginx
        networks:
            - docker_php
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

networks:
    docker_php:
